basic:
    name: cnn.com
    environments:
        production: 'https://cnn.com'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 375
        - 640
        - 720
        - 1200
        - 1280
        - 1920
    pages:
        - /
        - /us
        - /world
    monitoring:
        days: {  }
        type: daily
        schedule_time: '09:00 AM'
        schedule_time_zone: America/Los_Angeles
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
